# Generated by Django 3.2.7 on 2021-10-14 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0002_town_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='province.province'),
        ),
    ]
